AWSTemplateFormatVersion: 2010-09-09
Description: A SQL only IoT republish rule that responds to a siemens logo device

Resources:
  SQLRepublishTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: OfficeLightStatusRule
      TopicRulePayload:
        RuleDisabled: false
        Sql: SELECT CASE get(state.reported,"I..1:1-1") WHEN '01' THEN 'ON' ELSE 'OFF' END AS state from '$aws/things/siemens-logo/shadow/update' 
        Actions:
          - Republish:
              Topic: office/rgb1/light/status
              RoleArn: !GetAtt SQLRepublishRole.Arn
  
  SQLRepublishTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: OfficeLightSwitchRule
      TopicRulePayload:
        RuleDisabled: false
        Sql:  SELECT CASE command WHEN 'ON' THEN {'V..1:0.0-1': '01'} ELSE {'V..1:0.0-1': '01'} END AS state.desired from 'office/rgb1/light/switch'
        Actions:
          - Republish:
              Topic: $aws/things/siemens-logo/shadow/update
              RoleArn: !GetAtt SQLRepublishRole.Arn
  
  TopicRulePayload:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: siemens-logo-logs
      TopicRulePayload:
        RuleDisabled: false
        Sql: SELECT * from '$aws/things/siemens-logo/shadow/update' 
        Actions:
          - CloudwatchLogs:
              LogGroupName: office/rgb1/light/status
              RoleArn: !GetAtt IoTTopicRuleRole.Arn
  
  SQLRepublishRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - iot.amazonaws.com
      Policies:
        - PolicyName: SQLRepublishRuleRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iot:Publish
                Resource: !Join [ "", [ "arn:aws:iot:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":topic/output/*" ] ]
                
  TopicRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - iot.amazonaws.com
      Policies:
        - PolicyName: IoTTopicRuleRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                - logs:CreateLogStream
                - logs:DescribeLogStreams
                - logs:PutLogEvents
                Resource: !Join [ "", [ "arn:aws:iot:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":topic/output/*" ] ]
